theme: jekyll-theme-minimal
title: Sekani Warner - OSRE Catalyst ğŸ†
description: Blog detailing experiences, lessons, and perosnal growth while at UC Santa Cruz ğŸ›
logo: https://media.licdn.com/dms/image/D5603AQEk69F1ZR5LPA/profile-displayphoto-shrink_400_400/0/1677272457376?e=1694044800&v=beta&t=d4KHfA2IUXnHgTeR_Y86BoTwL8StxgOJCdgMHm24b84
